DECLARE @Perem CHAR(10)
SET @Perem = 'ÂÐÅÌß : '
SELECT @Perem + CAST(DATENAME(HOUR, GETDATE())AS CHAR(2))+':'+CAST(DATENAME(MINUTE, GETDATE())AS CHAR(2))+':'+
 CAST(DATENAME(SECOND, GETDATE())AS CHAR(2))