USE Радиостанции;
GO



CREATE TABLE dbo.BigDataBOSS1
(
ID_BOSS int PRIMARY KEY  NOT NULL,
BOSS_NAME nvarchar(50) NULL,
BOSS_SALARY money NULL DEFAULT 0
)

CREATE TABLE dbo.BigDataSUBORDINATE1
(
ID_SUBORDINATE int PRIMARY KEY  NOT NULL,
SUBORDINATE_NAME nvarchar(50) NOT NULL,
ID_BOSS int FOREIGN KEY REFERENCES BigDataBOSS ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
SUBORDINATE_SALARY money NOT NULL DEFAULT 0
)

