USE Радиостанции
GO
SET SHOWPLAN_TEXT ON
GO
SET STATISTICS IO ON; 
SELECT BigDataBOSS1.ID_BOSS FROM BigDataBOSS1  JOIN BigDataSUBORDINATE1 
   ON BigDataBOSS1.ID_BOSS=BigDataSUBORDINATE1.ID_SUBORDINATE OPTION (HASH JOIN)
GO
 
SET SHOWPLAN_TEXT OFF
GO
SET STATISTICS IO OFF; 

