USE Радиостанции
/*

UPDATE  TRAN_TABLE1   
SET   COLUMN_2  = 'FOUR'   WHERE COLUMN_1 = 4;   
SELECT * FROM TRAN_TABLE1


ALTER DATABASE Радиостанции  
SET READ_COMMITTED_SNAPSHOT ON;   
GO   
*/
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;   

GO   

 BEGIN TRANSACTION;   

SELECT * FROM TRAN_TABLE1 WHERE COLUMN_1=4  
ROLLBACK TRAN