--UPDATE  TRAN_TABLE1  
--SET   COLUMN_2='FOUR' WHERE COLUMN_1=4;

ALTER DATABASE Радиостанции 
--транзакции могут устанавливать уровень изоляции моментальных снимков:
SET ALLOW_SNAPSHOT_ISOLATION ON;
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;   

GO   

BEGIN TRAN   

SELECT * FROM TRAN_TABLE1 WHERE COLUMN_1=4  
ROLLBACK TRANSACTION   
GO   
