USE Радиостанции
GO
/*
UPDATE TRAN_TABLE1 SET COLUMN_2='пять' WHERE COLUMN_1=5
UPDATE TRAN_TABLE1 SET COLUMN_2='шесть' WHERE COLUMN_1=6
UPDATE TRAN_TABLE1 SET COLUMN_2='семь' WHERE COLUMN_1=7
SELECT * FROM TRAN_TABLE*/

--ПЕРВОЕ СОЕДИНЕНИЕ
BEGIN TRAN
UPDATE TRAN_TABLE1 SET COLUMN_2='ПЯТЬ' WHERE COLUMN_1=5 
SELECT * FROM TRAN_TABLE1
ROLLBACK TRAN