USE Радиостанции
GO

BEGIN TRAN 
UPDATE TRAN_TABLE1 SET COLUMN_2='ШЕСТЬ' WHERE COLUMN_1=6
	BEGIN TRAN
	UPDATE TRAN_TABLE1 SET COLUMN_2='ТРИ' WHERE COLUMN_1=3
	COMMIT TRAN
SELECT * FROM TRAN_TABLE1
ROLLBACK
SELECT * FROM TRAN_TABLE1
