BEGIN TRAN
	PRINT CAST(@@TRANCOUNT AS CHAR(1)) + ' транзакций на 1 уровне'
	UPDATE TRAN_TABLE1 SET COLUMN_2='пять' WHERE COLUMN_1=5
	BEGIN TRAN
		PRINT CAST(@@TRANCOUNT AS CHAR(1)) + ' транзакций на 2 уровне'
		UPDATE TRAN_TABLE1 SET COLUMN_2='четыре' WHERE COLUMN_1=4
		BEGIN TRAN 
			PRINT CAST(@@TRANCOUNT AS CHAR(1)) + ' транзакций на 3 уровне'
			UPDATE TRAN_TABLE1 SET COLUMN_2='три' WHERE COLUMN_1=3
			BEGIN TRAN 
				PRINT CAST(@@TRANCOUNT AS CHAR(1)) + ' транзакций на 2 уровне'
				UPDATE TRAN_TABLE1 SET COLUMN_2='два' WHERE COLUMN_1=2
				BEGIN TRAN 
					PRINT CAST(@@TRANCOUNT AS CHAR(1)) + ' транзакций на 1 уровне'
					UPDATE TRAN_TABLE1 SET COLUMN_2='один' WHERE COLUMN_1=1
				COMMIT
			COMMIT
		COMMIT
	COMMIT
	SELECT * FROM TRAN_TABLE1
	ROLLBACK TRANSACTION 