BEGIN TRAN
SELECT * FROM TRAN_TABLE1
SAVE TRANSACTION point1
DELETE FROM TRAN_TABLE1 WHERE COLUMN_1=6
SAVE TRANSACTION point2
DELETE FROM TRAN_TABLE1 WHERE COLUMN_1=5
SAVE TRANSACTION point3
DELETE FROM TRAN_TABLE1 WHERE COLUMN_1=4
SELECT * FROM TRAN_TABLE1
----------------------------
ROLLBACK TRANSACTION point3 
SELECT * FROM TRAN_TABLE1
----------------------------
ROLLBACK TRANSACTION point2 
SELECT * FROM TRAN_TABLE1
----------------------------
ROLLBACK TRANSACTION point1 
SELECT * FROM TRAN_TABLE1
COMMIT