SET STATISTICS IO ON; 
SELECT BigDataBOSS1.ID_BOSS, BigDataSUBORDINATE1.ID_SUBORDINATE, BigDataSUBORDINATE1.SUBORDINATE_NAME, BigDataBOSS1.BOSS_NAME
FROM BigDataBOSS1 JOIN BigDataSUBORDINATE1 ON BigDataBOSS1.ID_BOSS=BigDataSUBORDINATE1.ID_SUBORDINATE
SET STATISTICS IO OFF; 