USE Радиостанции
GO
--ПЕРВАЯ АВТОТРАНЗАКЦИЯ
CREATE TABLE TRAN_TABLE1
(
COLUMN_1 INT PRIMARY KEY,
COLUMN_2 VARCHAR(10) NOT NULL
)
--ВТОРАЯ АВТОТРАНЗАКЦИЯ
SELECT * FROM TRAN_TABLE1
--НЕЯВНАЯ ТРАНЗАКЦИЯ
SET IMPLICIT_TRANSACTIONS ON
INSERT INTO TRAN_TABLE1
VALUES
(1,'ONE'),
(2,'TWO'),
(3,'THREE')
COMMIT TRAN 
SELECT * FROM TRAN_TABLE1
INSERT INTO TRAN_TABLE1
VALUES
(4,'FOUR')
COMMIT TRAN SECOND_TRAN
SELECT * FROM TRAN_TABLE1
ROLLBACK TRAN 
SELECT * FROM TRAN_TABLE1
SET IMPLICIT_TRANSACTIONS OFF