BEGIN TRAN
	PRINT CAST(@@TRANCOUNT AS CHAR(1)) + '_1'
	SELECT * FROM TRAN_TABLE1
	UPDATE TRAN_TABLE1 SET COLUMN_2='ÒÐÈ' WHERE COLUMN_1=3
	BEGIN TRAN
		PRINT CAST(@@TRANCOUNT AS CHAR(1)) + '_2'
		UPDATE TRAN_TABLE1 SET COLUMN_2='ÄÂÀ' WHERE COLUMN_1=2
		BEGIN TRAN 
			PRINT CAST(@@TRANCOUNT AS CHAR(1)) + '_3'
			UPDATE TRAN_TABLE1 SET COLUMN_2='ÎÄÈÍ' WHERE COLUMN_1=1
		ROLLBACK
	SAVE TRAN POINT1
	COMMIT
ROLLBACK TRAN POINT1
